---
driver:
  name: dokken

provisioner:
  name: dokken

transport:
  name: dokken

verifier:
  name: inspec
  inspec_tests:
    - test/integration/default

platforms:
  # @see https://github.com/someara/dokken-images
  # @see https://hub.docker.com/r/dokken/
  - name: ubuntu-16.04
    driver:
      image: dokken/ubuntu-16.04
  - name: centos-7
    driver:
      image: dokken/centos-7

suites:
  - name: default
    run_list:
      - recipe[my_resolver::default]
    attributes:
  - name: attrs
    run_list:
      - recipe[my_resolver::default]
    attributes:
      my_resolver:
        nameservers:
          '1.1.1.1': false
          '8.8.8.8': false
          '1.0.0.1': true

